import { getDatabase } from './index';

export function seedTemplates() {
  const db = getDatabase();

  const templates = [
    // Exterior
    {
      title: 'Clean gutters',
      description: 'Remove leaves and debris from gutters and downspouts',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ seasons: ['spring', 'fall'] }),
    },
    {
      title: 'Power wash exterior',
      description: 'Clean siding, deck, and driveway',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Inspect roof',
      description: 'Check for damaged or missing shingles',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Seal driveway',
      description: 'Apply sealant to asphalt driveway',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ season: 'summer' }),
    },
    {
      title: 'Winterize outdoor faucets',
      description: 'Drain and cover outdoor water spigots',
      category: 'plumbing',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },

    // HVAC
    {
      title: 'Replace HVAC filters',
      description: 'Change air filters for heating and cooling system',
      category: 'hvac',
      recurrence_pattern: 'monthly',
      recurrence_interval: 3,
      recurrence_config: null,
    },
    {
      title: 'Service HVAC system',
      description: 'Professional maintenance of heating and cooling system',
      category: 'hvac',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Clean furnace',
      description: 'Clean burners and check furnace operation',
      category: 'hvac',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Service heat pump',
      description: 'Professional heat pump inspection and servicing',
      category: 'hvac',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },

    // Appliances
    {
      title: 'Clean dryer vent',
      description: 'Remove lint buildup from dryer exhaust vent',
      category: 'appliances',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: null,
    },
    {
      title: 'Clean refrigerator coils',
      description: 'Vacuum condenser coils on refrigerator',
      category: 'appliances',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: null,
    },
    {
      title: 'Replace water filter',
      description: 'Change refrigerator or whole-house water filter',
      category: 'appliances',
      recurrence_pattern: 'monthly',
      recurrence_interval: 6,
      recurrence_config: null,
    },
    {
      title: 'Clean dishwasher filter',
      description: 'Remove and clean dishwasher filter and spray arms',
      category: 'appliances',
      recurrence_pattern: 'monthly',
      recurrence_interval: 3,
      recurrence_config: null,
    },

    // Landscaping
    {
      title: 'Fertilize lawn',
      description: 'Apply seasonal fertilizer to lawn',
      category: 'landscaping',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ seasons: ['spring', 'fall'] }),
    },
    {
      title: 'Aerate lawn',
      description: 'Core aeration of lawn for better water and nutrient absorption',
      category: 'landscaping',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Prune trees and shrubs',
      description: 'Trim back overgrown branches',
      category: 'landscaping',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Mulch garden beds',
      description: 'Apply fresh mulch to garden beds',
      category: 'landscaping',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Winterize sprinkler system',
      description: 'Blow out irrigation lines and shut off water',
      category: 'landscaping',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },

    // Plumbing
    {
      title: 'Test sump pump',
      description: 'Pour water into sump pit to test pump operation',
      category: 'plumbing',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ seasons: ['spring', 'fall'] }),
    },
    {
      title: 'Flush water heater',
      description: 'Drain sediment from water heater tank',
      category: 'plumbing',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: null,
    },
    {
      title: 'Check for leaks',
      description: 'Inspect under sinks, around toilets, and exposed pipes',
      category: 'plumbing',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: null,
    },

    // Electrical
    {
      title: 'Test GFCI outlets',
      description: 'Press test button on all GFCI outlets',
      category: 'electrical',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: null,
    },
    {
      title: 'Test smoke detectors',
      description: 'Test all smoke and CO detectors, replace batteries',
      category: 'electrical',
      recurrence_pattern: 'monthly',
      recurrence_interval: 6,
      recurrence_config: null,
    },
    {
      title: 'Replace smoke detector batteries',
      description: 'Replace batteries in all smoke and CO detectors',
      category: 'electrical',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },

    // General
    {
      title: 'Deep clean carpets',
      description: 'Professional or DIY carpet cleaning',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Clean windows',
      description: 'Wash interior and exterior windows',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ seasons: ['spring', 'fall'] }),
    },
    {
      title: 'Check weatherstripping',
      description: 'Inspect and replace worn weatherstripping on doors and windows',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Clean kitchen exhaust fan',
      description: 'Remove and clean range hood filters',
      category: 'general',
      recurrence_pattern: 'monthly',
      recurrence_interval: 3,
      recurrence_config: null,
    },

    // Norwegian-specific templates
    {
      title: 'Winterize cabin',
      description: 'Prepare cabin for winter season',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Open cabin for summer',
      description: 'Prepare cabin for summer season after winter',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Service wood-burning stove',
      description: 'Clean and inspect wood stove',
      category: 'hvac',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Schedule chimney sweeping',
      description: 'Professional chimney inspection and cleaning',
      category: 'hvac',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Check for ice dams and roof load',
      description: 'Inspect roof for heavy snow and ice dams',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'winter' }),
    },
    {
      title: 'Maintain heating cables',
      description: 'Test and inspect heating cables on roof and gutters',
      category: 'electrical',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Clean HRV/ERV system',
      description: 'Clean balanced ventilation system filters and heat exchanger',
      category: 'hvac',
      recurrence_pattern: 'monthly',
      recurrence_interval: 6,
      recurrence_config: null,
    },
    {
      title: 'Check for moisture and mold',
      description: 'Inspect for moisture problems and mold growth',
      category: 'general',
      recurrence_pattern: 'monthly',
      recurrence_interval: 6,
      recurrence_config: null,
    },
    {
      title: 'Service dehumidifier',
      description: 'Clean and maintain dehumidifier',
      category: 'hvac',
      recurrence_pattern: 'monthly',
      recurrence_interval: 3,
      recurrence_config: null,
    },
    {
      title: 'Inspect crawl space',
      description: 'Check crawl space for moisture and damage',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: null,
    },
    {
      title: 'Winterize boat',
      description: 'Prepare boat for winter storage',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Service boat for season',
      description: 'Prepare boat for boating season',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Maintain pier/dock',
      description: 'Inspect and repair pier or dock',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'spring' }),
    },
    {
      title: 'Treat exterior wood surfaces',
      description: 'Oil or paint wooden panels and trim',
      category: 'exterior',
      recurrence_pattern: 'yearly',
      recurrence_interval: 2,
      recurrence_config: JSON.stringify({ season: 'summer' }),
    },
    {
      title: 'Service septic system',
      description: 'Pump and inspect septic system',
      category: 'plumbing',
      recurrence_pattern: 'yearly',
      recurrence_interval: 3,
      recurrence_config: null,
    },
    {
      title: 'Prepare ski equipment',
      description: 'Wax skis and check bindings for season',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Store summer equipment',
      description: 'Protect outdoor furniture and equipment for winter',
      category: 'general',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
    {
      title: 'Maintain outdoor lighting',
      description: 'Check and replace outdoor lights and sensors',
      category: 'electrical',
      recurrence_pattern: 'yearly',
      recurrence_interval: 1,
      recurrence_config: JSON.stringify({ season: 'fall' }),
    },
  ];

  const stmt = db.prepare(`
    INSERT OR IGNORE INTO task_templates (
      title, description, category,
      suggested_recurrence_type, suggested_recurrence_pattern,
      suggested_recurrence_interval, suggested_recurrence_config,
      is_system_template
    ) VALUES (?, ?, ?, ?, ?, ?, ?, 1)
  `);

  for (const template of templates) {
    stmt.run(
      template.title,
      template.description,
      template.category,
      template.recurrence_pattern, // suggested_recurrence_type (old column)
      template.recurrence_pattern, // suggested_recurrence_pattern (new column)
      template.recurrence_interval,
      template.recurrence_config
    );
  }

  console.log(`Seeded ${templates.length} task templates`);
}

export function seedTemplateSubtasks() {
  const db = getDatabase();

  const templateSubtasks: Record<string, string[]> = {
    'Clean gutters': [
      'Set up ladder safely on level ground',
      'Remove large debris by hand',
      'Flush gutters with garden hose',
      'Check and clear downspouts',
      'Clean up debris from ground',
      'Inspect for damage or loose sections',
    ],
    'Power wash exterior': [
      'Clear area of furniture and decorations',
      'Cover electrical outlets and fixtures',
      'Pre-treat stains with cleaning solution',
      'Power wash siding from top to bottom',
      'Clean deck and driveway',
      'Allow surfaces to dry completely',
    ],
    'Inspect roof': [
      'Use binoculars to inspect from ground (safer option)',
      'Look for missing or damaged shingles',
      'Check for moss or algae growth',
      'Inspect flashing around chimneys and vents',
      'Check for debris accumulation',
      'Document any issues with photos',
    ],
    'Seal driveway': [
      'Clean driveway thoroughly',
      'Repair any cracks with crack filler',
      'Allow repairs to cure (24-48 hours)',
      'Apply sealant in even coats',
      'Allow proper drying time',
      'Mark off area until fully cured',
    ],
    'Winterize outdoor faucets': [
      'Shut off interior water valves to outdoor faucets',
      'Drain water from outdoor faucets',
      'Remove and store garden hoses',
      'Install insulated faucet covers',
      'Check for leaks or drips',
    ],
    'Replace HVAC filters': [
      'Turn off HVAC system',
      'Locate and open filter compartment',
      'Remove old filter and note size',
      'Insert new filter (check airflow direction arrow)',
      'Close compartment securely',
      'Turn system back on and verify operation',
    ],
    'Service HVAC system': [
      'Schedule appointment with HVAC technician',
      'Provide clear access to equipment',
      'Review findings with technician',
      'Keep service records in maintenance log',
      'Schedule next service appointment',
    ],
    'Clean furnace': [
      'Turn off power and gas to furnace',
      'Remove furnace cover',
      'Vacuum burners and blower compartment',
      'Check and clean flame sensor',
      'Inspect heat exchanger for cracks',
      'Replace cover and restore power',
    ],
    'Service heat pump': [
      'Schedule appointment with HVAC technician',
      'Clear area around outdoor unit',
      'Review maintenance checklist with technician',
      'Ask about refrigerant levels',
      'Keep service records',
    ],
    'Clean dryer vent': [
      'Unplug dryer and pull away from wall',
      'Disconnect vent hose from back of dryer',
      'Use vent brush to clean vent duct',
      'Clean lint from vent hose',
      'Clean lint trap and housing',
      'Reconnect vent hose securely',
      'Push dryer back and test operation',
    ],
    'Clean refrigerator coils': [
      'Unplug refrigerator',
      'Locate condenser coils (usually on back or bottom)',
      'Vacuum coils using brush attachment',
      'Wipe down surrounding area',
      'Plug refrigerator back in',
      'Check that cooling resumes normally',
    ],
    'Replace water filter': [
      'Locate water filter (check manual if needed)',
      'Turn off water supply if required',
      'Remove old filter',
      'Install new filter according to instructions',
      'Run water for 3-5 minutes to flush',
      'Reset filter indicator light if present',
    ],
    'Clean dishwasher filter': [
      'Remove bottom dish rack',
      'Locate and remove filter assembly',
      'Rinse filter under running water',
      'Scrub with soft brush if needed',
      'Check and clean spray arm holes',
      'Reinstall filter and rack',
    ],
    'Fertilize lawn': [
      'Mow lawn before fertilizing',
      'Choose appropriate fertilizer for season',
      'Calibrate spreader according to instructions',
      'Apply fertilizer in overlapping rows',
      'Water lawn lightly after application',
      'Keep pets and children off lawn as directed',
    ],
    'Aerate lawn': [
      'Mark sprinkler heads and utilities',
      'Mow lawn shorter than usual',
      'Water lawn day before (soil should be moist)',
      'Use core aerator across entire lawn',
      'Leave soil plugs on lawn to break down',
      'Overseed if desired',
    ],
    'Prune trees and shrubs': [
      'Inspect plants for dead or diseased branches',
      'Sterilize pruning tools with rubbing alcohol',
      'Remove dead, damaged, or crossing branches',
      'Make clean cuts at proper angle',
      'Clear and dispose of cuttings',
      'Apply wound dressing to large cuts if needed',
    ],
    'Mulch garden beds': [
      'Pull weeds from garden beds',
      'Edge beds for clean appearance',
      'Calculate mulch needed (2-3 inches deep)',
      'Spread mulch evenly around plants',
      'Keep mulch away from plant stems',
      'Water beds lightly to settle mulch',
    ],
    'Winterize sprinkler system': [
      'Turn off water supply to sprinkler system',
      'Drain water from backflow preventer',
      'Set up air compressor (or hire professional)',
      'Blow out each zone systematically',
      'Insulate above-ground components',
      'Store removable components indoors',
    ],
    'Test sump pump': [
      'Locate sump pump in basement',
      'Pour 5 gallons of water into sump pit',
      'Verify pump activates automatically',
      'Check that water is pumped out properly',
      'Listen for unusual noises',
      'Test backup pump if present',
    ],
    'Flush water heater': [
      'Turn off power/gas to water heater',
      'Turn off cold water supply valve',
      'Connect garden hose to drain valve',
      'Run hose to floor drain or outside',
      'Open drain valve and pressure relief valve',
      'Drain until water runs clear',
      'Close valves, remove hose, refill tank',
      'Restore power/gas and check operation',
    ],
    'Check for leaks': [
      'Inspect under all sinks for moisture',
      'Check around toilet bases',
      'Examine exposed pipes in basement',
      'Look for water stains on ceilings',
      'Check water meter for hidden leaks',
      'Document any issues with photos',
    ],
    'Test GFCI outlets': [
      'Locate all GFCI outlets (bathrooms, kitchen, garage)',
      'Press TEST button on each outlet',
      'Verify power cuts off (test with nightlight)',
      'Press RESET button to restore power',
      'Check that reset is successful',
      'Replace any non-functioning GFCIs',
    ],
    'Test smoke detectors': [
      'Press and hold test button on each detector',
      'Verify alarm sounds loudly',
      'Test from multiple rooms to check volume',
      'Clean detector covers with vacuum',
      'Check battery level indicators',
      'Record test date on each detector',
    ],
    'Replace smoke detector batteries': [
      'Purchase correct battery type',
      'Remove detector from mounting bracket',
      'Replace old batteries with new ones',
      'Test detector before remounting',
      'Vacuum detector cover while open',
      'Record battery replacement date',
    ],
    'Deep clean carpets': [
      'Remove furniture and clear floor',
      'Vacuum thoroughly to remove loose dirt',
      'Pre-treat stains and high-traffic areas',
      'Rent or prepare carpet cleaning machine',
      'Clean carpets in overlapping sections',
      'Open windows and run fans to dry',
      'Vacuum again after carpets are fully dry',
    ],
    'Clean windows': [
      'Gather supplies (squeegee, cleaner, rags)',
      'Remove screens and clean separately',
      'Wash exterior windows first',
      'Clean interior windows',
      'Wipe window sills and tracks',
      'Reinstall screens',
    ],
    'Check weatherstripping': [
      'Inspect all exterior doors for gaps',
      'Check window weatherstripping',
      'Test with dollar bill (should have resistance)',
      'Remove and replace worn weatherstripping',
      'Check door sweeps at bottom',
      'Test doors for proper seal',
    ],
    'Clean kitchen exhaust fan': [
      'Turn off power to range hood',
      'Remove filter (check manual for type)',
      'Soak filter in hot soapy water or dishwasher',
      'Wipe down hood interior and exterior',
      'Scrub filter if needed',
      'Dry and reinstall filter',
      'Test fan operation',
    ],
    'Winterize cabin': [
      'Shut off main water supply',
      'Drain all water lines and fixtures',
      'Add antifreeze to drains and toilets',
      'Empty and clean refrigerator, leave door open',
      'Remove all food and perishables',
      'Close and lock all windows and shutters',
      'Unplug all electrical devices',
      'Set heat to minimum (5-8°C) or drain heating system',
    ],
    'Open cabin for summer': [
      'Inspect exterior for winter damage',
      'Open shutters and air out cabin',
      'Turn on water supply and check for leaks',
      'Test all faucets and flush toilets',
      'Clean and sanitize surfaces',
      'Check heating and electrical systems',
      'Test smoke and CO detectors',
      'Remove winterization materials',
    ],
    'Service wood-burning stove': [
      'Remove and dispose of ash when cool',
      'Clean glass door with appropriate cleaner',
      'Vacuum firebox and ash pan',
      'Inspect door gasket for wear',
      'Check firebricks for cracks',
      'Clean baffle plate if applicable',
      'Test door seal with paper test',
      'Stock up on firewood if needed',
    ],
    'Schedule chimney sweeping': [
      'Find certified chimney sweep (feiermester)',
      'Schedule appointment before heating season',
      'Provide access to fireplace and roof',
      'Review sweep\'s findings and recommendations',
      'Keep receipt for insurance/documentation',
      'Note next service date',
    ],
    'Check for ice dams and roof load': [
      'Visually inspect roof from ground',
      'Look for icicles along eaves (sign of ice dams)',
      'Check for sagging roof areas from snow weight',
      'Inspect attic for water stains or moisture',
      'Remove snow from roof if necessary (hire professional)',
      'Check that heating cables are working',
    ],
    'Maintain heating cables': [
      'Visually inspect cables for damage',
      'Test cables before first freeze',
      'Check thermostat/sensor operation',
      'Clear debris from cable areas',
      'Ensure cables are properly secured',
      'Replace any damaged sections',
    ],
    'Clean HRV/ERV system': [
      'Turn off ventilation system',
      'Remove and clean or replace filters',
      'Clean heat exchanger core (follow manual)',
      'Vacuum intake and exhaust vents',
      'Check condensation drain',
      'Restart system and verify operation',
    ],
    'Check for moisture and mold': [
      'Inspect basement and crawl space',
      'Check bathrooms and kitchen for moisture',
      'Look for condensation on windows',
      'Check closets and storage areas',
      'Use moisture meter if available',
      'Note any musty odors',
      'Take photos of any problem areas',
    ],
    'Service dehumidifier': [
      'Empty water reservoir',
      'Clean filter with vacuum or water',
      'Wipe down exterior and reservoir',
      'Check drain hose if applicable',
      'Clean or replace air filter',
      'Test operation',
    ],
    'Inspect crawl space': [
      'Check for standing water or moisture',
      'Inspect vapor barrier for damage',
      'Look for signs of pests or animals',
      'Check insulation condition',
      'Inspect foundation for cracks',
      'Verify ventilation is adequate',
      'Take photos for records',
    ],
    'Winterize boat': [
      'Flush and drain engine cooling system',
      'Add fuel stabilizer and fill tank',
      'Change engine oil and filter',
      'Drain fresh water system',
      'Remove and store batteries',
      'Clean and cover boat',
      'Store life jackets and equipment indoors',
    ],
    'Service boat for season': [
      'Inspect hull for damage',
      'Check engine oil and coolant',
      'Install and charge batteries',
      'Test all electrical systems',
      'Check safety equipment (life jackets, fire extinguisher)',
      'Verify registration and insurance are current',
      'Stock emergency supplies',
    ],
    'Maintain pier/dock': [
      'Inspect pilings and supports for rot',
      'Check deck boards for damage',
      'Tighten or replace loose hardware',
      'Test railing stability',
      'Clear debris and vegetation',
      'Repair or replace damaged sections',
    ],
    'Treat exterior wood surfaces': [
      'Clean surface with appropriate cleaner',
      'Allow to dry completely (2-3 days)',
      'Sand rough areas if needed',
      'Apply wood oil or paint as appropriate',
      'Use brush for detailed areas',
      'Allow proper curing time',
      'Clean brushes and tools',
    ],
    'Service septic system': [
      'Schedule pumping with licensed service',
      'Locate and expose septic tank lid',
      'Have tank pumped and inspected',
      'Ask about tank condition and sludge levels',
      'Check drainage field for issues',
      'Keep service records',
      'Plan next service (typically 2-5 years)',
    ],
    'Prepare ski equipment': [
      'Clean ski bases thoroughly',
      'Apply appropriate temperature wax',
      'Scrape and brush wax',
      'Inspect and adjust bindings',
      'Check ski edges for damage',
      'Test release settings on bindings',
      'Organize ski clothing and accessories',
    ],
    'Store summer equipment': [
      'Clean all furniture and equipment',
      'Dry thoroughly to prevent mold',
      'Apply protective covers',
      'Store cushions indoors',
      'Drain and store garden hoses',
      'Put away or cover grill',
      'Store tools in dry location',
    ],
    'Maintain outdoor lighting': [
      'Replace burned-out bulbs',
      'Clean fixture lenses and covers',
      'Test motion sensors',
      'Check timer settings',
      'Inspect wiring for damage',
      'Tighten loose fixtures',
      'Consider upgrading to LED bulbs',
    ],
  };

  // Seed subtasks for each template
  const subtaskStmt = db.prepare(`
    INSERT INTO template_subtasks (template_id, text, position)
    SELECT id, ?, ? FROM task_templates WHERE title = ?
  `);

  let totalSubtasks = 0;
  for (const [templateTitle, subtasksArray] of Object.entries(templateSubtasks)) {
    subtasksArray.forEach((subtaskText, index) => {
      subtaskStmt.run(subtaskText, index, templateTitle);
      totalSubtasks++;
    });
  }

  console.log(`Seeded ${totalSubtasks} template subtasks across ${Object.keys(templateSubtasks).length} templates`);
}
